{% set name = "django-tenants" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-tenants-{{ version }}.tar.gz
  sha256: 233c6bcc5643e3c5acf6c7d429f5b8106bba088f5dde3a8b3154e9417a456bcc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=2.1,<5.1

test:
  imports:
    - django_tenants
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-tenants/django-tenants
  summary: Tenant support for Django using PostgreSQL schemas.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
